### ISSUE TITLE
relocate from typesafehub to Lightbend org

### ISSUE THREAD

**Issue by SethTisue** [lightbend/lightbend-markdown#7]

**Comment by SethTisue** [comment]
@TimMoore ?

**Comment by TimMoore** [comment]
Thanks for the mention, @SethTisue. I wasn't watching this repo until now.

I'll move it, but I guess I need to write a README first.

**Comment by SethTisue** [comment]
short and sweet's fine :-)

**Comment by TimMoore** [comment]
https://github.com/typesafehub/lightbend-markdown/pull/8

**Comment by TimMoore** [comment]
Also added a `LICENSE` file in #9.

**Comment by TimMoore** [comment]
Done https://github.com/lightbend/lightbend-markdown

**Comment by SethTisue** [comment]
thank you!
